name: Publicar en PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Build and publish
      uses: pypa/gh-action-pypi-publish@master
      with:
        token: ${{ secrets.PYPI_API_TOKEN }}
